export enum DomainErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED',
  NOMINATION_ALREADY_REGISTERED = 'NOMINATION_ALREADY_REGISTERED',
  INVALID_NOMINATION_SCORE = 'INVALID_NOMINATION_SCORE',
}
